from .chart import ResultChart
from .clock import Clock
from .device_pannel import DevicePannel
from .gauge_pannel import GaugePanel
from .monitor import GPUUsageMonitor,CPUUsageMonitor
from .new_widget import InferRessult
from .pie import Pie
from .process_ring import ProgressRing
from .temperature import ThermometreDlg
from .scatter import Scatter
